/*
 * Contenido del juego.
 *
 * Cada entrada es [picante, texto, extras?]
 *   picante: 0 = para todo el mundo, 1 = un poco picante, 2 = picante
 *   texto:   {p} = persona a la que le toca, {p2} = otra persona al azar
 *   extras:  { n: tragos que cuesta pagar, dura: cartas que dura una regla,
 *              todos: true si todo el mundo bebe de su vaso (con o sin alcohol),
 *              min: personas mínimas para que la carta tenga sentido }
 *
 * Los ids se generan como "tipo-índice", así que las cartas nuevas se añaden
 * siempre al final de su lista.
 */
(function (root) {
  'use strict';

  var RAW = {
    yonunca: [
      [0, 'Yo nunca he fingido que me sabía una canción en un concierto.'],
      [0, 'Yo nunca me he pasado de parada por quedarme dormido en el transporte público.'],
      [0, 'Yo nunca he cotilleado el perfil de alguien hasta llegar a fotos de hace años.'],
      [0, 'Yo nunca he dado like sin querer a una foto antigua mientras cotilleaba.'],
      [0, 'Yo nunca he mentido sobre mi edad.'],
      [0, 'Yo nunca he llorado viendo una película de dibujos.'],
      [0, 'Yo nunca he ido a clase o a trabajar con una prenda del revés.'],
      [0, 'Yo nunca he olvidado el nombre de alguien justo después de que me lo dijera.'],
      [0, 'Yo nunca he fingido una llamada para no hablar con alguien.'],
      [0, 'Yo nunca me he comido algo que se había caído al suelo.'],
      [0, 'Yo nunca he mandado un audio de más de cinco minutos.'],
      [0, 'Yo nunca he cancelado un plan por pereza y me he inventado otra excusa.'],
      [0, 'Yo nunca he saludado a alguien que en realidad saludaba a otra persona.'],
      [0, 'Yo nunca he buscado el móvil mientras lo tenía en la mano.'],
      [0, 'Yo nunca he suspendido el examen del carné de conducir.'],
      [0, 'Yo nunca he pedido comida a domicilio dos veces el mismo día.'],
      [0, 'Yo nunca he dicho «ya voy» cuando todavía estaba en la ducha.'],
      [0, 'Yo nunca he dicho «estoy de camino» sin haber salido de casa.'],
      [0, 'Yo nunca me he colado en una fiesta sin invitación.'],
      [0, 'Yo nunca he hecho una captura de una conversación para enseñársela a otra persona.'],
      [0, 'Yo nunca he roto algo en una casa ajena y no he dicho nada.'],
      [0, 'Yo nunca he tenido una conversación entera con una mascota.'],
      [0, 'Yo nunca he fingido que me encantaba un regalo.'],
      [0, 'Yo nunca me he visto una serie entera en un fin de semana.'],
      [0, 'Yo nunca me he reído en un momento serio sin poder parar.'],
      [0, 'Yo nunca he aprobado un examen sin haber estudiado nada.'],
      [0, 'Yo nunca he pedido en un restaurante señalando la foto del menú.'],
      [0, 'Yo nunca he cantado en un karaoke.'],
      [0, 'Yo nunca he subido algo a redes y lo he borrado a los cinco minutos.'],
      [0, 'Yo nunca he tropezado en público y he seguido andando como si nada.'],
      [0, 'Yo nunca he silenciado el grupo de WhatsApp de la familia.'],
      [0, 'Yo nunca he desayunado pizza fría.'],
      [0, 'Yo nunca he dicho que había visto una película que no había visto.'],
      [0, 'Yo nunca he escrito y borrado el mismo mensaje más de tres veces.'],
      [0, 'Yo nunca he vuelto de fiesta cuando ya era de día.'],
      [0, 'Yo nunca me he quedado sin batería en el peor momento posible.'],
      [0, 'Yo nunca he perdido las llaves de casa.'],
      [0, 'Yo nunca he hecho ghosting a alguien.'],
      [0, 'Yo nunca he aprendido una coreografía de TikTok.'],
      [0, 'Yo nunca me he dormido en una fiesta.'],
      [0, 'Yo nunca he usado el traductor del móvil para hablar con alguien en persona.'],
      [0, 'Yo nunca he llegado tarde a mi propia celebración.'],
      [0, 'Yo nunca he cantado una canción entera inventándome la letra.'],
      [0, 'Yo nunca he leído los mensajes de alguien por encima de su hombro.'],
      [0, 'Yo nunca he hablado mal de alguien y al girarme estaba detrás.'],
      [0, 'Yo nunca he ido al súper solo a por una cosa y he salido sin ella.'],
      [0, 'Yo nunca me he hecho una foto con un famoso.'],
      [0, 'Yo nunca he fingido saber de vinos.'],
      [1, 'Yo nunca he tenido un crush con alguien de este grupo.'],
      [1, 'Yo nunca he ligado por una app de citas.'],
      [1, 'Yo nunca he tenido una cita a ciegas.'],
      [1, 'Yo nunca me he liado con alguien en una previa.'],
      [1, 'Yo nunca he escrito a mi ex estando de fiesta.'],
      [1, 'Yo nunca he dado un beso en la primera cita.'],
      [1, 'Yo nunca he cambiado de acera para no cruzarme con un ex.'],
      [1, 'Yo nunca he usado una frase para ligar malísima… y ha funcionado.'],
      [1, 'Yo nunca he tenido un crush con un profesor o una profesora.'],
      [1, 'Yo nunca me he pillado de alguien que no sabía ni que yo existía.'],
      [1, 'Yo nunca he hecho match con alguien que ya conocía.'],
      [1, 'Yo nunca he cotilleado el perfil de la nueva pareja de un ex.'],
      [1, 'Yo nunca he tenido un amor de verano.'],
      [1, 'Yo nunca he fingido que me gustaba algo solo para ligar.'],
      [2, 'Yo nunca he mandado un mensaje subido de tono al chat equivocado.'],
      [2, 'Yo nunca me he liado con alguien sin saber su nombre.'],
      [2, 'Yo nunca he besado a más de una persona la misma noche.'],
      [2, 'Yo nunca he vuelto con un ex después de una noche de fiesta.'],
      [2, 'Yo nunca me he liado con alguien de este grupo.'],
      [2, 'Yo nunca he dado un beso en un sitio en el que no tocaba.'],
      [2, 'Yo nunca he tenido una cita que acabó en desayuno.'],
      [2, 'Yo nunca he mentido sobre dónde había pasado la noche.'],
      [2, 'Yo nunca he ligado con alguien del trabajo o de clase.'],
      [2, 'Yo nunca he hecho algo atrevido para ganar una apuesta.']
    ],

    probable: [
      [0, '¿Quién es más probable que se haga viral en internet?'],
      [0, '¿Quién es más probable que se duerma antes de que acabe la fiesta?'],
      [0, '¿Quién es más probable que pierda el móvil esta noche?'],
      [0, '¿Quién es más probable que se case en Las Vegas?'],
      [0, '¿Quién es más probable que monte una empresa y se forre?'],
      [0, '¿Quién es más probable que sobreviva a un apocalipsis zombi?'],
      [0, '¿Quién es más probable que acabe viviendo en otro continente?'],
      [0, '¿Quién es más probable que llegue tarde a su propia boda?'],
      [0, '¿Quién es más probable que llore con un anuncio de la tele?'],
      [0, '¿Quién es más probable que se apunte a un reality?'],
      [0, '¿Quién es más probable que conteste a un audio con otro audio de diez minutos?'],
      [0, '¿Quién es más probable que adopte cinco gatos?'],
      [0, '¿Quién es más probable que se pierda volviendo a casa esta noche?'],
      [0, '¿Quién es más probable que gane un concurso de la tele?'],
      [0, '¿Quién es más probable que se ría en el peor momento?'],
      [0, '¿Quién es más probable que tenga una cuenta secreta en redes?'],
      [0, '¿Quién es más probable que organice la próxima quedada?'],
      [0, '¿Quién es más probable que acabe la noche cantando?'],
      [0, '¿Quién es más probable que abra una nevera ajena sin preguntar?'],
      [0, '¿Quién es más probable que pida comida rápida al volver a casa?'],
      [0, '¿Quién es más probable que empiece una discusión sobre la tortilla con o sin cebolla?'],
      [0, '¿Quién es más probable que se ponga a bailar sin música?'],
      [0, '¿Quién es más probable que haga amistades en la cola del baño?'],
      [0, '¿Quién es más probable que invente la excusa más creativa para no ir a trabajar?'],
      [0, '¿Quién es más probable que monte un drama por algo mínimo?'],
      [0, '¿Quién es más probable que pague el gimnasio un año y no vaya nunca?'],
      [0, '¿Quién es más probable que siga saliendo de fiesta a los ochenta?'],
      [0, '¿Quién es más probable que salga en las noticias por algo absurdo?'],
      [0, '¿Quién es más probable que se olvide de que había quedado?'],
      [0, '¿Quién es más probable que aprenda chino solo para pedir bien en un restaurante?'],
      [0, '¿Quién es más probable que se haga influencer?'],
      [0, '¿Quién es más probable que haga la mejor paella del grupo?'],
      [1, '¿Quién es más probable que se enamore esta noche?'],
      [1, '¿Quién es más probable que vuelva con su ex?'],
      [1, '¿Quién es más probable que tenga más matches en las apps de ligar?'],
      [1, '¿Quién es más probable que ligue esta noche?'],
      [1, '¿Quién es más probable que escriba a su ex esta noche?'],
      [1, '¿Quién es más probable que tenga una cita con alguien famoso?'],
      [1, '¿Quién es más probable que se case primero?'],
      [1, '¿Quién es más probable que tenga un crush secreto en este grupo?'],
      [2, '¿Quién es más probable que tenga la historia de una noche más loca?'],
      [2, '¿Quién es más probable que se líe con alguien esta noche?'],
      [2, '¿Quién es más probable que haya tenido la cita más desastrosa?'],
      [2, '¿Quién es más probable que tenga el historial amoroso más intenso?'],
      [2, '¿Quién es más probable que desaparezca de la fiesta sin despedirse… y con compañía?']
    ],

    pregunta: [
      [0, '{p}, ¿qué es lo más raro que has comido?'],
      [0, '{p}, ¿cuál es tu placer culpable musical?'],
      [0, '{p}, ¿cuál ha sido tu mejor excusa para escaquearte de un plan?'],
      [0, '{p}, ¿qué es lo primero que harías si te tocaran diez millones mañana?'],
      [0, '{p}, ¿con qué famoso o famosa te irías de cañas?'],
      [0, '{p}, ¿cuál es la peor moda que has seguido?'],
      [0, '{p}, si tuvieras un superpoder inútil, ¿cuál sería?'],
      [0, '{p}, si tu vida fuera una película, ¿qué título tendría?'],
      [0, '{p}, ¿qué es lo más ridículo por lo que has llorado?'],
      [0, '{p}, ¿cuál ha sido tu peor trabajo?'],
      [0, '{p}, ¿qué opinión impopular defiendes a muerte?'],
      [0, '{p}, ¿qué fue lo último que buscaste en internet? Léelo en voz alta.'],
      [0, '{p}, ¿cuál fue tu primera impresión de {p2}?'],
      [0, '{p}, ¿qué tres cosas te llevarías a una isla desierta?'],
      [0, '{p}, ¿cuál ha sido tu momento más torpe de este año?'],
      [0, '{p}, ¿qué te gusta muchísimo aunque te cueste admitirlo?'],
      [0, '{p}, ¿qué canción sonaría en tu entrada triunfal a cualquier sitio?'],
      [0, '{p}, ¿qué habilidad absurda tienes?'],
      [0, '{p}, ¿cuál es la peor excusa que has puesto por llegar tarde?'],
      [0, '{p}, ¿a qué personaje de ficción te pareces más?'],
      [0, '{p}, si pudieras cambiarte un día por alguien de este grupo, ¿por quién y por qué?'],
      [0, '{p}, ¿qué es lo más espontáneo que has hecho nunca?'],
      [0, '{p}, ¿cuál es tu peor manía?'],
      [0, '{p}, ¿qué es lo que más echas de menos de tu infancia?'],
      [0, '{p}, ¿cuál es el mejor plan que has hecho con {p2}?'],
      [0, '{p}, del 1 al 10, ¿cómo de bien bailas? El grupo decide si mientes.'],
      [0, '{p}, ¿cuál es la anécdota de fiesta que siempre acabas contando?'],
      [0, '{p}, ¿cuál es el mejor consejo que te han dado?'],
      [0, '{p}, ¿qué es lo que más te gusta de {p2}?'],
      [0, '{p}, ¿qué comida no soportas aunque a todo el mundo le guste?'],
      [0, '{p}, ¿qué app abres más veces al día? Enseña el tiempo de pantalla.'],
      [0, '{p}, ¿cuál es tu mayor miedo absurdo?'],
      [0, '{p}, ¿quién de este grupo sería peor compañero de piso y por qué?'],
      [0, '{p}, ¿cuál ha sido tu viaje más desastroso?'],
      [1, '{p}, ¿qué es lo primero en lo que te fijas cuando alguien te gusta?'],
      [1, '{p}, ¿cuál ha sido tu peor cita?'],
      [1, '{p}, ¿cuál es tu mayor red flag en una relación?'],
      [1, '{p}, ¿cuál es la mejor (o la peor) frase para ligar que te han dicho?'],
      [1, '{p}, ¿has tenido un crush con alguien de este grupo? No hace falta decir con quién.'],
      [1, '{p}, describe a tu tipo ideal en tres palabras.'],
      [1, '{p}, ¿qué famoso o famosa es tu amor platónico?'],
      [1, '{p}, ¿cuál es el mensaje más cutre que has mandado para ligar?'],
      [1, '{p}, ¿cuánto tiempo hace de tu último beso?'],
      [1, '{p}, ¿cómo sería tu primera cita perfecta?'],
      [1, '{p}, ¿quién de este grupo crees que liga más? ¿Por qué?'],
      [1, '{p}, ¿qué es lo más romántico que has hecho por alguien?'],
      [1, '{p}, ¿qué te hace perder el interés por alguien al instante?'],
      [2, '{p}, ¿cuál es el sitio más raro donde has dado un beso?'],
      [2, '{p}, ¿qué es lo más atrevido que has hecho por alguien que te gustaba?'],
      [2, '{p}, ¿cuál es tu historia de ligoteo más loca?'],
      [2, '{p}, si tuvieras que tener una cita con alguien de este grupo, ¿con quién sería?'],
      [2, '{p}, ¿qué parte de tu cuerpo te gusta más?'],
      [2, '{p}, ¿has mandado alguna vez una foto atrevida? Basta con un sí o un no.'],
      [2, '{p}, ¿de qué lío te arrepientes más?'],
      [2, '{p}, ¿qué es lo que más te atrae de {p2}?']
    ],

    reto: [
      [0, '{p}, habla con el acento que elija el grupo hasta tu próximo turno.'],
      [0, '{p}, imita a alguien del grupo hasta que lo adivinen. Tienes 30 segundos.'],
      [0, '{p}, cuenta un chiste. Si nadie se ríe, tienes que contar otro.'],
      [0, '{p}, baila 20 segundos la canción que elija {p2}.'],
      [0, '{p}, narra lo que está pasando en la fiesta como en un documental de animales. 30 segundos.'],
      [0, '{p}, haz 15 sentadillas mientras el grupo cuenta en voz alta.'],
      [0, '{p}, responde a tres preguntas del grupo sin decir «sí» ni «no».'],
      [0, '{p}, haz un brindis épico de 20 segundos en honor a {p2}.'],
      [0, '{p}, intercambia una prenda con {p2} (chaqueta, gorra, calcetín…) hasta tu próximo turno.'],
      [0, '{p}, haz una declaración de amor dramática a un cojín, una planta o lo que tengas a mano.'],
      [0, '{p}, canta el estribillo de la canción que elija el grupo.'],
      [0, '{p}, sirve la siguiente bebida a todo el grupo, con o sin alcohol según cada cual.'],
      [0, '{p}, di diez países en 30 segundos.'],
      [0, '{p}, dibuja a {p2} en 30 segundos y enséñale el resultado.'],
      [0, '{p}, habla de ti en tercera persona hasta tu próximo turno.'],
      [0, '{p}, vende el objeto que tengas más cerca como en la teletienda. 30 segundos.'],
      [0, '{p}, imita a cinco animales. El grupo elige cuáles.'],
      [0, '{p}, sal de la sala y vuelve a entrar como una estrella de rock.'],
      [0, '{p}, haz reír a alguien del grupo en menos de 30 segundos.'],
      [0, '{p}, cuenta tu película favorita en 15 segundos.'],
      [0, '{p}, lee en voz alta el último mensaje que has enviado, sin decir a quién.'],
      [0, '{p}, habla como un robot hasta tu próximo turno.'],
      [0, '{p}, haz el baile más ridículo que te sepas durante 15 segundos.'],
      [0, '{p}, inventa en un minuto una historia en la que salga todo el grupo.'],
      [0, '{p}, haz una reseña de esta fiesta como si fuera un restaurante en Google Maps.'],
      [0, '{p}, ponte un vaso de plástico en la cabeza y da una vuelta a la sala sin que se caiga.'],
      [0, '{p}, copia la forma de hablar de {p2} hasta tu próximo turno.'],
      [0, '{p}, di sin equivocarte: «Tres tristes tigres tragaban trigo en un trigal».'],
      [0, '{p}, deja que el grupo te ponga un mote. Os llamaréis así hasta tu próximo turno.'],
      [0, '{p}, manda un 🍍 a la tercera persona de tus chats recientes y no expliques nada.'],
      [0, '{p}, aguanta 30 segundos a la pata coja mientras dices el abecedario.'],
      [0, '{p}, haz tu mejor pose de modelo y deja que {p2} te haga una foto.'],
      [0, '{p}, di el abecedario al revés lo más rápido que puedas.'],
      [0, '{p}, haz de presentador de telediario y da la noticia más importante de la noche.'],
      [0, '{p}, deja que {p2} te haga un peinado nuevo. Lo llevas hasta tu próximo turno.'],
      [0, '{p}, aplaude cada vez que alguien beba o pague hasta tu próximo turno.'],
      [1, '{p}, dile un piropo creativo a {p2}. El grupo lo puntúa del 1 al 10.', { min: 3 }],
      [1, '{p}, mira a {p2} con tu mejor cara seductora durante 5 segundos sin reírte.'],
      [1, '{p}, intenta ligar con {p2} usando solo frases de canciones.'],
      [1, '{p}, describe tu cita perfecta como si fuera un anuncio de colonia.'],
      [1, '{p}, deja que {p2} escriba tu bio de app de ligar y léela en voz alta.'],
      [1, '{p}, declárate a {p2} como en una telenovela.'],
      [1, '{p}, enséñanos cómo ligas cuando estás de fiesta.'],
      [1, '{p}, susurra a {p2} el mejor piropo que se te ocurra.'],
      [1, '{p}, baila una lenta de 20 segundos con {p2}. Si alguien no quiere, con un cojín.'],
      [1, '{p}, pon tu cara de cuando alguien te gusta.'],
      [2, '{p}, haz un baile sexy de 15 segundos… a una silla.'],
      [2, '{p}, enseña los dos últimos mensajes con tu crush.'],
      [2, '{p}, da un beso en la mejilla a quien elijas del grupo, si le parece bien.'],
      [2, '{p}, di en tres palabras lo que te parece más atractivo de {p2}.'],
      [2, '{p}, escribe «Hola, ¿qué tal?» a tu crush y enseña la respuesta si llega antes de que acabe la partida.'],
      [2, '{p}, cuenta en 30 segundos tu cita más atrevida, con todo el misterio que puedas.'],
      [2, '{p}, haz un masaje de hombros de 20 segundos a quien quiera recibirlo.']
    ],

    duelo: [
      [0, '{p} contra {p2}: piedra, papel o tijera al mejor de tres.'],
      [0, '{p} contra {p2}: duelo de miradas. Quien parpadee o se ría primero, pierde.'],
      [0, '{p} contra {p2}: pulso de pulgares al mejor de tres.'],
      [0, '{p} contra {p2}: por turnos, decid palabras que empiecen por «ca». Quien se quede en blanco o repita, pierde.'],
      [0, '{p} contra {p2}: por turnos, decid marcas de coche. Quien falle, pierde.'],
      [0, '{p} contra {p2}: batalla de rap de 15 segundos por cabeza. El grupo decide.', { min: 3 }],
      [0, '{p} contra {p2}: el grupo elige un animal. Gana la mejor imitación.', { min: 3 }],
      [0, '{p} contra {p2}: a la pata coja. Quien apoye el pie primero, pierde.'],
      [0, '{p} contra {p2}: concurso de caras raras. El grupo vota.', { min: 3 }],
      [0, '{p} contra {p2}: el resto intenta haceros reír. Quien aguante más serio, gana.', { min: 3 }],
      [0, '{p} contra {p2}: el grupo piensa en un famoso y vosotros preguntáis por turnos cosas de sí o no. Quien lo adivine, gana.', { min: 3 }],
      [0, '{p} contra {p2}: decid «El cielo está enladrillado, ¿quién lo desenladrillará?». Gana quien lo diga mejor.', { min: 3 }],
      [0, '{p} contra {p2}: lanzad una bola de papel a un vaso. Tres intentos cada uno.'],
      [0, '{p} contra {p2}: contad hasta 30 por turnos, pero en los múltiplos de 3 hay que decir «Shanghai». Quien falle, pierde.'],
      [0, '{p} contra {p2}: por turnos, decid canciones de reguetón. Quien se quede en blanco, pierde.'],
      [0, '{p} contra {p2}: cadena de memoria. Decid por turnos una palabra repitiendo todas las anteriores. Quien falle, pierde.'],
      [0, '{p} contra {p2}: el grupo pone una canción. Quien adivine antes el título, gana.', { min: 3 }],
      [0, '{p} contra {p2}: quien diga más rápido el nombre completo de todo el grupo, gana.'],
      [1, '{p} contra {p2}: gana la mejor frase para ligar. Vota el grupo.', { min: 3 }],
      [1, '{p} contra {p2}: posad para la portada de una revista romántica. Vota el grupo.', { min: 3 }]
    ],

    grupo: [
      [0, 'Pagan todas las personas que lleven algo negro.'],
      [0, 'Paga quien tenga menos batería en el móvil. Comprobadlo.', { n: 2 }],
      [0, 'Paga la última persona que llegó a la fiesta.'],
      [0, 'Pagan quienes tengan hermanos.'],
      [0, 'Paga quien tenga el cumpleaños más cercano.'],
      [0, '¡Brindis! Todo el mundo levanta su vaso y bebe, con o sin alcohol.', { todos: true }],
      [0, 'Paga quien haya mirado el móvil durante la última carta.'],
      [0, 'Pagan quienes hayan estado en más de cinco países.'],
      [0, 'A la de tres, todo el mundo se toca la nariz. La última persona en hacerlo, paga.'],
      [0, 'A la de tres, todo el mundo levanta la mano. La última persona en hacerlo, paga.'],
      [0, 'Paga quien tenga la foto de perfil más antigua.'],
      [0, 'Pagan quienes hayan dicho una palabrota en los últimos cinco minutos.'],
      [0, 'Paga quien tenga más notificaciones sin leer.'],
      [0, 'A la de tres, todo el mundo señala a quien mejor viste esta noche. Esa persona elige quién paga.', { min: 3 }],
      [0, 'Silencio absoluto durante 30 segundos. Quien hable primero, paga.', { n: 2 }],
      [0, 'Paga quien tenga el nombre más largo.'],
      [0, 'Pagan quienes lleven gafas o lentillas.'],
      [0, 'Pagan quienes hayan nacido en invierno.'],
      [0, 'Paga la persona más joven del grupo.'],
      [0, 'Paga quien haya viajado más lejos de casa.'],
      [0, 'Pagan quienes todavía no hayan bailado esta noche.'],
      [0, '{p} elige a dos personas. Las dos pagan.', { min: 3 }],
      [0, '¡Ronda de agua! Todo el mundo bebe un trago de agua. Sí, hasta los 🍺.', { todos: true }],
      [0, 'Paga quien tenga el móvil con la pantalla más rota.'],
      [0, 'A la de tres, todo el mundo dice un número del 1 al 5. Quienes coincidan, pagan.'],
      [0, 'Brindis por {p}: todo el mundo bebe de su vaso y {p} da las gracias con un discurso.', { todos: true }],
      [1, 'Pagan quienes estén sin pareja.'],
      [1, 'Pagan quienes hayan tenido una cita este mes.'],
      [1, 'Pagan quienes tengan una app de ligar instalada ahora mismo.'],
      [2, 'Pagan quienes hayan dado un beso esta semana.'],
      [2, 'Pagan quienes hayan escrito a un ex este año.']
    ],

    categoria: [
      [0, 'Marcas de cerveza'],
      [0, 'Bebidas sin alcohol'],
      [0, 'Países de Asia'],
      [0, 'Personajes de Disney'],
      [0, 'Canciones del verano'],
      [0, 'Cosas que hay en una cocina'],
      [0, 'Futbolistas'],
      [0, 'Series de Netflix'],
      [0, 'Ciudades de España'],
      [0, 'Palabras que rimen con «fiesta»'],
      [0, 'Comidas que lleven queso'],
      [0, 'Excusas para no ir a trabajar'],
      [0, 'Marcas de ropa'],
      [0, 'Superhéroes'],
      [0, 'Cantantes o grupos de los 2000'],
      [0, 'Animales que empiecen por «p»'],
      [0, 'Cócteles'],
      [0, 'Cosas que se pierden en una fiesta'],
      [0, 'Platos de comida china'],
      [0, 'Palabras en inglés que usamos en español'],
      [0, 'Personajes de los Simpson'],
      [0, 'Cosas que se pueden comprar en un chino'],
      [1, 'Cosas que se hacen en una primera cita'],
      [1, 'Apodos cariñosos para una pareja'],
      [1, 'Sitios donde ligar'],
      [2, 'Excusas para no volver a casa'],
      [2, 'Canciones para un momento romántico']
    ],

    regla: [
      [0, 'Nadie puede decir «beber» ni «trago». Quien lo diga, paga.', { dura: 8 }],
      [0, '{p} es quien manda en los pulgares: cuando ponga el pulgar en la mesa, todo el mundo tiene que hacerlo. La última persona, paga.', { dura: 10 }],
      [0, 'Hay que hablar como en una peli de piratas. Quien se olvide, paga.', { dura: 5 }],
      [0, 'Prohibido señalar con el dedo. Quien lo haga, paga.', { dura: 8 }],
      [0, 'Antes de hablar hay que decir «con todo el respeto». Quien se olvide, paga.', { dura: 6 }],
      [0, '{p} manda en las preguntas: quien conteste a una pregunta de {p}, paga.', { dura: 8 }],
      [0, 'Prohibido decir nombres. Usad apodos. Quien diga un nombre, paga.', { dura: 6 }],
      [0, 'Quien se toque la cara, paga.', { dura: 6 }],
      [0, 'Quien diga «tío» o «tía», paga.', { dura: 8 }],
      [0, 'El vaso se coge con la mano izquierda, lleve lo que lleve. Quien use la derecha, paga.', { dura: 8 }],
      [0, 'Prohibido tocar el móvil. Quien lo toque, paga.', { dura: 6 }],
      [0, '{p} y {p2} van en pack: cuando una de las dos personas paga, la otra también.', { dura: 10 }],
      [0, 'Hay que acabar cada frase con «en Shanghai». Quien se olvide, paga.', { dura: 5 }],
      [0, 'Prohibido decir «sí» y «no». Quien lo diga, paga.', { dura: 5 }],
      [0, 'Cada vez que alguien pague, el resto tiene que aplaudir. Quien no aplauda, paga.', { dura: 8 }],
      [0, '{p} tiene que hablar susurrando. Si se le olvida, paga.', { dura: 6 }],
      [1, 'Cada vez que alguien se ría, tiene que decir un piropo a quien tenga a la derecha. Si no se le ocurre, paga.', { dura: 6 }]
    ]
  };

  /* Alternativas para quien no bebe alcohol. Nivel 1 = rápido, nivel 2 = algo más largo. */
  var CASTIGOS = [
    [1, 'Haz 10 sentadillas mientras el grupo cuenta.'],
    [1, 'Di sin equivocarte: «Pablito clavó un clavito, ¿qué clavito clavó Pablito?».'],
    [1, 'Haz tu mejor pose de modelo durante 5 segundos.'],
    [1, 'Cuenta un chiste malo.'],
    [1, 'Imita al animal que elija el grupo.'],
    [1, 'Habla como un robot hasta tu próximo turno.'],
    [1, 'Di en 10 segundos cinco palabras que empiecen por la letra que elija el grupo.'],
    [1, 'Haz un brindis de 10 segundos por la persona de tu izquierda.'],
    [1, 'Da un sorbo a tu bebida con el meñique levantado y acento pijo.'],
    [1, 'Haz una reverencia exagerada a todo el grupo.'],
    [1, 'Aguanta 15 segundos sin reírte mientras el grupo intenta hacerte reír.'],
    [1, 'Canta «Cumpleaños feliz» con voz de ópera.'],
    [1, 'Di tres cosas buenas de la persona de tu derecha.'],
    [1, 'Haz el ruido de un coche de carreras durante 5 segundos.'],
    [2, 'Baila 20 segundos la canción que elija el grupo.'],
    [2, 'Haz 20 sentadillas mientras el grupo cuenta.'],
    [2, 'Deja que el grupo te ponga un mote hasta tu próximo turno.'],
    [2, 'Aguanta 30 segundos haciendo la plancha.'],
    [2, 'Canta el estribillo de la canción que elija el grupo.'],
    [2, 'Habla con el acento que elija el grupo hasta tu próximo turno.'],
    [2, 'Haz de camarero: rellena el vaso de quien te lo pida en la próxima carta.'],
    [2, 'No puedes decir «sí» ni «no» hasta tu próximo turno.'],
    [2, 'Vende como en la teletienda el objeto que elija el grupo.'],
    [2, 'Imita a alguien del grupo hasta que lo adivinen.']
  ];

  var cards = [];
  Object.keys(RAW).forEach(function (type) {
    RAW[type].forEach(function (entry, i) {
      var extra = entry[2] || {};
      var card = { id: type + '-' + i, type: type, hot: entry[0], text: entry[1] };
      if (extra.n) card.n = extra.n;
      if (extra.dura) card.dura = extra.dura;
      if (extra.todos) card.todos = true;
      if (extra.min) card.min = extra.min;
      cards.push(card);
    });
  });

  var castigos = CASTIGOS.map(function (entry, i) {
    return { id: 'castigo-' + i, nivel: entry[0], text: entry[1] };
  });

  var data = { cards: cards, castigos: castigos };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
  } else {
    root.PREVIA_DATA = data;
  }
})(typeof window !== 'undefined' ? window : this);
