/*
 * Contenido del juego.
 *
 * Cada entrada es [picante, texto, extras?]
 *   picante: 0 = para todo el mundo, 1 = ligoteo, 2 = picante, 3 = sin filtro (solo adultos)
 *   texto:   {p} = persona a la que le toca, {p2} = otra persona al azar
 *   extras:  { n: tragos que cuesta pagar, dura: cartas que dura una regla,
 *              todos: true si todo el mundo bebe de su vaso (con o sin alcohol),
 *              min: personas mínimas para que la carta tenga sentido }
 *
 * Los ids se generan como "tipo-índice", así que las cartas nuevas se añaden
 * siempre al final de su lista.
 *
 * Los retos con contacto físico siempre dicen «si le parece bien»: nadie tiene
 * que tocar ni dejarse tocar si no quiere. Negarse es pasar, y pasar es pagar.
 */
(function (root) {
  'use strict';

  var RAW = {
    yonunca: [
      [0, 'Yo nunca he leído el móvil de otra persona a escondidas.'],
      [0, 'Yo nunca he hablado mal de alguien de este grupo a sus espaldas.'],
      [0, 'Yo nunca he mentido en este juego.'],
      [0, 'Yo nunca he fingido estar con fiebre para no ir a clase o a trabajar.'],
      [0, 'Yo nunca he robado algo en una tienda.'],
      [0, 'Yo nunca he llorado por alguien que no se lo merecía.'],
      [0, 'Yo nunca he vomitado en una fiesta.'],
      [0, 'Yo nunca me he despertado sin saber cómo llegué a casa.'],
      [0, 'Yo nunca me he colado en un concierto, una discoteca o el metro sin pagar.'],
      [0, 'Yo nunca he dicho «te quiero» sin sentirlo.'],
      [0, 'Yo nunca he cotilleado el móvil de una pareja.'],
      [0, 'Yo nunca he tenido una cuenta falsa para cotillear a alguien.'],
      [0, 'Yo nunca he dejado en visto a alguien de este grupo a propósito.'],
      [0, 'Yo nunca he mentido a mis padres sobre dónde iba a dormir.'],
      [0, 'Yo nunca he echado la culpa a otra persona de algo que hice yo.'],
      [0, 'Yo nunca me he tirado un pedo y he culpado a otra persona.'],
      [0, 'Yo nunca he regalado algo que me habían regalado a mí.'],
      [0, 'Yo nunca he copiado en un examen.'],
      [0, 'Yo nunca he estado enfadado con alguien de este grupo sin que lo supiera.'],
      [0, 'Yo nunca he contado un secreto que me habían pedido guardar.'],
      [0, 'Yo nunca he dicho «estoy de camino» sin haber salido de casa.'],
      [0, 'Yo nunca he vuelto de fiesta cuando ya era de día.'],
      [0, 'Yo nunca me he dormido en el baño de una discoteca o de una casa.'],
      [0, 'Yo nunca he fingido una llamada para huir de una conversación.'],
      [0, 'Yo nunca he cotilleado el perfil de alguien hasta llegar a fotos de hace años.'],
      [0, 'Yo nunca he mandado una captura de una conversación para criticar a alguien.'],
      [0, 'Yo nunca he silenciado a alguien de este grupo en redes.'],
      [0, 'Yo nunca he salido de fiesta un lunes y he ido a trabajar o a clase al día siguiente.'],
      [0, 'Yo nunca he perdido el móvil de fiesta.'],
      [0, 'Yo nunca he hecho algo de lo que me arrepiento en un viaje.'],
      [0, 'Yo nunca he fingido que no me acordaba de algo que había hecho de fiesta.'],
      [0, 'Yo nunca he dicho que no podía quedar con alguien de aquí para quedar con otra gente.'],
      [0, 'Yo nunca me he ido de un restaurante sin pagar.'],
      [0, 'Yo nunca he buscado mi propio nombre en Google.'],
      [1, 'Yo nunca he tenido un crush con alguien de este grupo.'],
      [1, 'Yo nunca he ligado por una app de citas.'],
      [1, 'Yo nunca me he liado con alguien en una previa.'],
      [1, 'Yo nunca he escrito a mi ex con unas copas de más.'],
      [1, 'Yo nunca he dado un beso en la primera cita.'],
      [1, 'Yo nunca he tenido una cita a ciegas.'],
      [1, 'Yo nunca he ido a una cita solo por la cena gratis.'],
      [1, 'Yo nunca he hecho match con alguien que ya conocía.'],
      [1, 'Yo nunca me he liado con un amigo o una amiga de mi ex.'],
      [1, 'Yo nunca he tonteado con dos personas a la vez sin que lo supieran.'],
      [1, 'Yo nunca he cotilleado el perfil de la nueva pareja de un ex.'],
      [1, 'Yo nunca me he liado con alguien que se llevara más de diez años conmigo.'],
      [1, 'Yo nunca me he pillado de alguien que tenía pareja.'],
      [1, 'Yo nunca he tonteado con alguien solo para dar celos.'],
      [1, 'Yo nunca he fingido que me gustaba algo solo para ligar.'],
      [1, 'Yo nunca he tenido un amor de verano.'],
      [1, 'Yo nunca he besado a alguien por una apuesta.'],
      [1, 'Yo nunca he ligado con un camarero o una camarera.'],
      [2, 'Yo nunca me he liado con alguien de este grupo.'],
      [2, 'Yo nunca he puesto los cuernos.'],
      [2, 'Yo nunca me he liado con alguien sin saber su nombre.'],
      [2, 'Yo nunca he besado a más de una persona la misma noche.'],
      [2, 'Yo nunca he mandado una foto subida de tono.'],
      [2, 'Yo nunca he mandado un mensaje subido de tono al chat equivocado.'],
      [2, 'Yo nunca he tenido un rollo de una noche.'],
      [2, 'Yo nunca he vuelto con un ex solo por una noche.'],
      [2, 'Yo nunca me he liado con alguien en el baño de una discoteca.'],
      [2, 'Yo nunca he hecho un baile sexy a alguien.'],
      [2, 'Yo nunca he tenido una cita que acabó en desayuno.'],
      [2, 'Yo nunca me he liado con alguien del trabajo o de clase.'],
      [2, 'Yo nunca he dormido en casa de alguien a quien acababa de conocer.'],
      [2, 'Yo nunca he hecho sexting.'],
      [2, 'Yo nunca me he liado con dos personas del mismo grupo de amigos.'],
      [2, 'Yo nunca he tenido una relación de amigos con derecho a roce.'],
      [2, 'Yo nunca he tenido un sueño erótico con alguien de este grupo.'],
      [2, 'Yo nunca me he liado con alguien que tenía pareja.'],
      [3, 'Yo nunca he fingido un orgasmo.'],
      [3, 'Yo nunca lo he hecho en un coche.'],
      [3, 'Yo nunca lo he hecho en la playa o al aire libre.'],
      [3, 'Yo nunca he hecho un trío.'],
      [3, 'Yo nunca he usado un juguete sexual.'],
      [3, 'Yo nunca me he grabado o he hecho fotos durante el sexo.'],
      [3, 'Yo nunca lo he hecho en casa de mis padres con ellos dentro.'],
      [3, 'Yo nunca lo he hecho en un baño público.'],
      [3, 'Yo nunca me he acostado con alguien en la primera cita.'],
      [3, 'Yo nunca me he acostado con alguien cuyo nombre no recuerdo.'],
      [3, 'Yo nunca me he acostado con un ex después de cortar.'],
      [3, 'Yo nunca me han pillado haciéndolo.'],
      [3, 'Yo nunca lo he hecho más de tres veces en un mismo día.'],
      [3, 'Yo nunca he mandado nudes.'],
      [3, 'Yo nunca me he acostado con alguien de este grupo.'],
      [3, 'Yo nunca he hecho un striptease.'],
      [3, 'Yo nunca he usado esposas, vendas o algo parecido.'],
      [3, 'Yo nunca he tenido sexo por videollamada.']
    ],

    probable: [
      [0, '¿Quién es más probable que acabe alguna vez en comisaría?'],
      [0, '¿Quién es más probable que se haga viral por hacer el ridículo?'],
      [0, '¿Quién es más probable que pierda el móvil esta noche?'],
      [0, '¿Quién es más probable que se case en Las Vegas con alguien que acaba de conocer?'],
      [0, '¿Quién es más probable que termine la noche llorando?'],
      [0, '¿Quién es más probable que cuente sin querer un secreto de este grupo esta noche?'],
      [0, '¿Quién es más probable que deje a alguien por WhatsApp?'],
      [0, '¿Quién es más probable que se haga rico y deje de hablarnos?'],
      [0, '¿Quién es más probable que tenga una cuenta secreta en redes?'],
      [0, '¿Quién es más probable que se duerma antes de que acabe la previa?'],
      [0, '¿Quién es más probable que llegue tarde a su propia boda?'],
      [0, '¿Quién es más probable que monte un drama por algo mínimo?'],
      [0, '¿Quién es más probable que desaparezca de la fiesta sin despedirse?'],
      [0, '¿Quién es más probable que se gaste el sueldo entero en una noche?'],
      [0, '¿Quién es más probable que lea los mensajes de otra persona a escondidas?'],
      [0, '¿Quién es más probable que haya mentido ya en este juego?'],
      [0, '¿Quién es más probable que acabe la noche cantando en la calle?'],
      [0, '¿Quién es más probable que vomite esta noche?'],
      [0, '¿Quién es más probable que se quede en la fiesta hasta que nos echen?'],
      [0, '¿Quién es más probable que tenga más secretos que no conocemos?'],
      [0, '¿Quién es más probable que cotillee más sobre la vida de los demás?'],
      [0, '¿Quién es más probable que se mude a otro país sin avisar?'],
      [0, '¿Quién es más probable que se haga un tatuaje del que se arrepienta?'],
      [0, '¿Quién es más probable que sobreviva más días en un reality de supervivencia?'],
      [0, '¿Quién es más probable que se pelee con un desconocido esta noche?'],
      [0, '¿Quién es más probable que acabe siendo famoso por algo absurdo?'],
      [1, '¿Quién es más probable que se enamore esta noche?'],
      [1, '¿Quién es más probable que vuelva con su ex?'],
      [1, '¿Quién es más probable que tenga más matches en las apps de ligar?'],
      [1, '¿Quién es más probable que ligue esta noche?'],
      [1, '¿Quién es más probable que escriba a su ex esta noche?'],
      [1, '¿Quién es más probable que tenga un crush secreto en este grupo?'],
      [1, '¿Quién es más probable que se case primero?'],
      [1, '¿Quién es más probable que ligue con el camarero o la camarera?'],
      [1, '¿Quién es más probable que tenga el peor gusto para ligar?'],
      [1, '¿Quién es más probable que use la misma frase para ligar con todo el mundo?'],
      [1, '¿Quién es más probable que aprenda chino solo para ligar en Shanghai?'],
      [2, '¿Quién es más probable que se líe con alguien esta noche?'],
      [2, '¿Quién es más probable que haya puesto los cuernos alguna vez?'],
      [2, '¿Quién es más probable que tenga la lista de rollos más larga?'],
      [2, '¿Quién es más probable que mande una foto subida de tono esta noche?'],
      [2, '¿Quién es más probable que se líe con alguien de este grupo?'],
      [2, '¿Quién es más probable que desaparezca de la fiesta… con compañía?'],
      [2, '¿Quién es más probable que tenga un rollo con su jefe o su jefa?'],
      [2, '¿Quién es más probable que tenga el historial amoroso más intenso?'],
      [3, '¿Quién es más probable que tenga la fantasía más rara?'],
      [3, '¿Quién es más probable que haya hecho un trío?'],
      [3, '¿Quién es más probable que tenga un juguete sexual escondido en casa ahora mismo?'],
      [3, '¿Quién es más probable que lo haya hecho en el sitio más raro?'],
      [3, '¿Quién es más probable que se abra un OnlyFans?'],
      [3, '¿Quién es más probable que se le oiga desde la habitación de al lado?'],
      [3, '¿Quién es más probable que haya tenido más parejas sexuales?']
    ],

    pregunta: [
      [0, '{p}, ¿a quién de este grupo no le contarías nunca un secreto?'],
      [0, '{p}, ¿con quién de aquí no te irías de viaje? ¿Por qué?'],
      [0, '{p}, ¿cuál es la mentira más gorda que les has contado a tus padres?'],
      [0, '{p}, ¿qué es lo peor que has hecho con unas copas de más?'],
      [0, '{p}, ¿qué es lo que más te molesta de {p2}?'],
      [0, '{p}, ¿qué es lo que más te gusta de {p2}?'],
      [0, '{p}, ¿qué pensaste de {p2} la primera vez que os visteis? ¿Ha cambiado?'],
      [0, '{p}, ¿de qué te arrepientes más de este último año?'],
      [0, '{p}, ¿cuál es el secreto más gordo que puedes contar sin meter en líos a nadie?'],
      [0, '{p}, ¿a quién de aquí llamarías para esconder un cadáver?'],
      [0, '{p}, ¿quién de aquí crees que tiene más secretos?'],
      [0, '{p}, ¿qué es lo peor que has dicho de alguien de este grupo?'],
      [0, '{p}, enseña la última foto de tu galería.'],
      [0, '{p}, ¿qué fue lo último que buscaste en internet? Léelo en voz alta.'],
      [0, '{p}, cuenta tu peor borrachera en 30 segundos.'],
      [0, '{p}, ¿qué opinión impopular defiendes a muerte?'],
      [0, '{p}, ¿quién de aquí crees que tendrá la vida más loca dentro de diez años?'],
      [0, '{p}, ¿qué es lo más vergonzoso que te ha pasado en una fiesta?'],
      [0, '{p}, ¿has robado algo alguna vez? ¿El qué?'],
      [0, '{p}, ¿a quién de este grupo le tenías manía al principio?'],
      [0, '{p}, ¿qué es lo que nunca le has dicho a {p2}?'],
      [0, '{p}, puntúa del 1 al 10 lo bien que te cae cada persona del grupo.', { min: 3 }],
      [0, '{p}, ¿qué foto tuya borrarías de internet si pudieras?'],
      [0, '{p}, ¿qué es lo más caro que has roto sin confesarlo?'],
      [0, '{p}, enseña tu tiempo de pantalla de esta semana.'],
      [0, '{p}, ¿qué mensaje de tu móvil no querrías que viera nadie de aquí? No hace falta enseñarlo.'],
      [0, '{p}, del 1 al 10, ¿cuánto has mentido en este juego?'],
      [0, '{p}, ¿a quién de aquí le has mentido alguna vez? ¿Sobre qué?'],
      [0, '{p}, ¿cuál es la peor decisión que has tomado de fiesta?'],
      [0, '{p}, ¿quién de aquí es más falso o falsa en redes sociales?', { min: 3 }],
      [0, '{p}, si mañana tuvieras que irte a vivir con alguien de aquí, ¿con quién? ¿Y con quién nunca?', { min: 3 }],
      [0, '{p}, ¿qué es lo más raro que tienes en el historial de búsqueda?'],
      [1, '{p}, ¿quién de este grupo te parece más atractivo o atractiva?', { min: 3 }],
      [1, '{p}, ¿con quién de aquí tendrías una cita?'],
      [1, '{p}, cuenta tu peor cita. Con detalles.'],
      [1, '{p}, ¿cuál es tu mayor red flag?'],
      [1, '{p}, ¿te ha gustado alguna vez la pareja de alguien que conoces?'],
      [1, '{p}, ¿a qué ex volverías a escribir esta noche?'],
      [1, '{p}, ¿cuánto hace de tu último beso? ¿Con quién?'],
      [1, '{p}, ¿quién crees que besa mejor de este grupo?', { min: 3 }],
      [1, '{p}, ¿qué es lo primero en lo que te fijas de alguien que te gusta?'],
      [1, '{p}, ¿cuál es la frase para ligar que mejor te ha funcionado? Úsala con {p2}.'],
      [1, '{p}, ¿qué te hace perder el interés por alguien al instante?'],
      [1, '{p}, ¿a quién de aquí presentarías a tus padres como pareja?'],
      [1, '{p}, ¿qué famoso o famosa es tu pase libre?'],
      [1, '{p}, ¿has ligado con alguien solo por interés?'],
      [1, '{p}, ¿con quién estás hablando o tonteando ahora mismo?'],
      [2, '{p}, ¿con quién de este grupo te liarías si no hubiera consecuencias?'],
      [2, '{p}, ¿has tenido un crush con alguien de este grupo? Esta vez hay que decir con quién.'],
      [2, '{p}, enseña el último chat con alguien con quien estés tonteando.'],
      [2, '{p}, ¿cuál es el sitio más raro donde te has liado con alguien?'],
      [2, '{p}, ¿has puesto alguna vez los cuernos? ¿Y te los han puesto a ti?'],
      [2, '{p}, ¿cuál es tu historia de una noche más loca?'],
      [2, '{p}, ¿qué es lo más atrevido que te han dicho por mensaje?'],
      [2, '{p}, ¿a cuántas personas has besado este año?'],
      [2, '{p}, ¿cuál es tu récord de personas besadas en una misma noche?'],
      [2, '{p}, ¿has mandado alguna vez una foto subida de tono? ¿A quién?'],
      [2, '{p}, ¿qué es lo que más te pone de alguien?'],
      [2, '{p}, ¿quién de aquí crees que es mejor en la cama?', { min: 3 }],
      [2, '{p}, ¿de qué rollo te arrepientes más?'],
      [2, '{p}, ¿te has liado alguna vez con alguien para dar celos a otra persona?'],
      [2, '{p}, ¿qué es lo más atrevido que has hecho por alguien que te gustaba?'],
      [2, '{p}, ¿qué parte del cuerpo de {p2} te parece más sexy?'],
      [3, '{p}, ¿qué fantasía sexual tienes todavía pendiente?'],
      [3, '{p}, ¿cuál es el sitio más raro donde lo has hecho?'],
      [3, '{p}, ¿con cuántas personas te has acostado?'],
      [3, '{p}, ¿cuál es tu postura favorita?'],
      [3, '{p}, ¿harías un trío? ¿Con quién, si pudieras elegir a cualquiera?'],
      [3, '{p}, ¿cuál ha sido tu peor experiencia en la cama?'],
      [3, '{p}, ¿has fingido alguna vez en la cama? ¿Por qué?'],
      [3, '{p}, ¿qué es lo más raro que te han pedido en la cama?'],
      [3, '{p}, ¿cuándo fue la última vez que lo hiciste?'],
      [3, '{p}, ¿qué es lo que más te gusta que te hagan?'],
      [3, '{p}, ¿tienes algún juguete sexual? ¿Cuál?'],
      [3, '{p}, ¿con quién de este grupo te acostarías?'],
      [3, '{p}, ¿te han pillado alguna vez haciéndolo? Cuéntalo.'],
      [3, '{p}, ¿qué es lo más atrevido que has hecho en la cama?'],
      [3, '{p}, ¿has tenido algún sueño erótico con alguien de aquí? ¿Con quién?'],
      [3, '{p}, ¿cuál es tu mejor polvo? Cuéntalo sin decir el nombre.']
    ],

    reto: [
      [0, '{p}, deja que el grupo lea en voz alta tus cinco últimas búsquedas de Google.'],
      [0, '{p}, llama a alguien de tus contactos y cántale el «Cumpleaños feliz». Si no es su cumpleaños, mejor.'],
      [0, '{p}, deja que {p2} escriba un mensaje desde tu móvil a quien quiera. Tú lo lees antes de enviarlo y no puedes vetarlo.'],
      [0, '{p}, imita a alguien del grupo hasta que lo adivinen. Tienes 30 segundos.'],
      [0, '{p}, habla con el acento que elija el grupo hasta tu próximo turno.'],
      [0, '{p}, baila 20 segundos la canción que elija {p2}.'],
      [0, '{p}, manda un audio cantando a la tercera persona de tus chats recientes.'],
      [0, '{p}, deja tu móvil bocarriba en el centro: hasta tu próximo turno, se leen en voz alta todas tus notificaciones.'],
      [0, '{p}, deja que el grupo elija tu foto de perfil de WhatsApp para las próximas 24 horas.'],
      [0, '{p}, escribe «Te echo de menos» a la última persona con la que hablaste y no lo expliques hasta mañana.'],
      [0, '{p}, haz 20 sentadillas mientras el grupo cuenta.'],
      [0, '{p}, intercambia una prenda con {p2} hasta el final de la partida.'],
      [0, '{p}, narra lo que pasa en la fiesta como un documental de animales durante 30 segundos.'],
      [0, '{p}, enseña tu historial de YouTube o de TikTok.'],
      [0, '{p}, lee en voz alta el último mensaje que has enviado.'],
      [0, '{p}, deja que {p2} te peine o te maquille como quiera. Lo llevas toda la partida.'],
      [0, '{p}, imita a {p2} cuando va de fiesta.'],
      [0, '{p}, di algo bonito y sincero de cada persona del grupo.', { min: 3 }],
      [0, '{p}, di una cosa que te moleste de cada persona del grupo.', { min: 3 }],
      [0, '{p}, manda un 🍍 a la tercera persona de tus chats recientes y no expliques nada.'],
      [0, '{p}, vende como en la teletienda el objeto que tengas más cerca.'],
      [0, '{p}, deja que el grupo te ponga un mote para el resto de la noche.'],
      [0, '{p}, cambia el nombre de {p2} en tus contactos por el que elija el grupo.'],
      [0, '{p}, sube a tus historias la foto que elija el grupo de tu galería.'],
      [0, '{p}, sirve la siguiente bebida a todo el grupo, con o sin alcohol según cada cual.'],
      [0, '{p}, cuenta un chiste. Si nadie se ríe, pagas igualmente.'],
      [0, '{p}, habla en tercera persona hasta tu próximo turno.'],
      [0, '{p}, enseña la conversación de WhatsApp que tienes fijada arriba del todo.'],
      [0, '{p}, deja que {p2} mire tu galería durante 10 segundos.'],
      [0, '{p}, escribe al grupo de la familia «Tengo algo que contaros» y no digas nada más hasta mañana.'],
      [1, '{p}, dile un piropo creativo a {p2}. El grupo lo puntúa del 1 al 10.', { min: 3 }],
      [1, '{p}, intenta ligar con {p2} usando solo frases de canciones.'],
      [1, '{p}, declárate a {p2} como en una telenovela.'],
      [1, '{p}, mira a {p2} a los ojos durante 10 segundos sin reírte.'],
      [1, '{p}, enséñanos cómo ligas de fiesta. {p2} hace de víctima.'],
      [1, '{p}, deja que {p2} escriba tu bio de app de ligar y léela en voz alta.'],
      [1, '{p}, dale like a la última foto de tu ex.'],
      [1, '{p}, enseña tu último match o la última conversación que tengas en una app de ligar.'],
      [1, '{p}, baila una lenta de 20 segundos con {p2}, si os parece bien. Si no, con un cojín.'],
      [1, '{p}, susurra a {p2} lo que más te gusta de su físico.'],
      [1, '{p}, escribe a tu crush «¿Qué haces esta noche?» y enseña la respuesta si llega.'],
      [1, '{p}, dile a {p2} la frase para ligar más cutre que sepas, con total seriedad.'],
      [2, '{p}, haz un baile sexy de 15 segundos a una silla, o a {p2} si le parece bien.'],
      [2, '{p}, da un beso en la mejilla a la persona del grupo que más te atraiga, si le parece bien.'],
      [2, '{p}, enseña los últimos mensajes con la persona con la que más tonteas.'],
      [2, '{p}, haz un masaje de hombros de 30 segundos a quien elijas, si le apetece.'],
      [2, '{p}, quítate una prenda hasta el final de la partida (calcetines y accesorios valen).'],
      [2, '{p}, pon la cara que pones cuando alguien te pone.'],
      [2, '{p}, di en tres palabras lo más sexy de {p2}.'],
      [2, '{p}, deja que {p2} lea tu última conversación con tu ex.'],
      [2, '{p}, siéntate encima de {p2} hasta tu próximo turno, si le parece bien.'],
      [2, '{p}, manda «No dejo de pensar en ti» a quien elija el grupo de entre tus cinco últimos chats.'],
      [2, '{p}, ponle voz sexy a la lista de la compra. 20 segundos.'],
      [3, '{p}, haz tu mejor gemido de película.'],
      [3, '{p}, da un beso a quien elijas del grupo, donde quieras, si le parece bien.', { n: 3 }],
      [3, '{p}, describe tu noche perfecta con alguien de este grupo sin decir quién. El resto tiene que adivinarlo.', { min: 3 }],
      [3, '{p}, cuenta tu última vez en 30 segundos.'],
      [3, '{p}, haz un baile erótico de 20 segundos a quien quiera recibirlo.'],
      [3, '{p}, enseña con un cojín tu postura favorita.'],
      [3, '{p}, quítate una prenda de verdad (no valen accesorios) hasta el final de la partida.', { n: 3 }],
      [3, '{p}, susurra a {p2} lo que le harías en una noche juntos.'],
      [3, '{p}, deja que {p2} te dé un beso en el cuello, si os parece bien a los dos.', { n: 3 }],
      [3, '{p}, enseña la foto más atrevida de tu galería.', { n: 3 }]
    ],

    prefieres: [
      [0, '¿Prefieres saber cuándo vas a morir o cómo vas a morir?'],
      [0, '¿Prefieres que se lea en voz alta tu historial de búsqueda o tus últimos WhatsApp?'],
      [0, '¿Prefieres vivir sin música o sin series?'],
      [0, '¿Prefieres ser famoso por algo vergonzoso o no ser famoso nunca?'],
      [0, '¿Prefieres perder el móvil o la cartera esta noche?'],
      [0, '¿Prefieres que tus padres vean tu historial o que tu jefe vea tus redes?'],
      [0, '¿Prefieres ir siempre diez minutos tarde o siempre veinte minutos antes?'],
      [0, '¿Prefieres una semana de resaca o un mes sin salir?'],
      [0, '¿Prefieres ganar un millón sin poder contarlo o no ganarlo y que todo el mundo crea que sí?'],
      [0, '¿Prefieres oler siempre a ajo o a sudor?'],
      [0, '¿Prefieres pasar siempre calor o siempre frío?'],
      [0, '¿Prefieres leer mentes o ser invisible?'],
      [0, '¿Prefieres vivir en Shanghai sin hablar chino o en un pueblo sin internet?'],
      [0, '¿Prefieres un viaje con {p} o un viaje con {p2}?'],
      [0, '¿Prefieres un año sin redes sociales o un año sin salir de fiesta?'],
      [0, '¿Prefieres que se publique tu peor foto o tu peor audio?'],
      [0, '¿Prefieres saber lo que piensa de ti todo el grupo o que nadie sepa nunca lo que piensas tú?'],
      [0, '¿Prefieres que te toque compartir piso con {p} o con {p2}?'],
      [0, '¿Prefieres decir siempre la verdad o no poder volver a hablar en público?'],
      [0, '¿Prefieres que todo el grupo lea tu diario de los 15 años o tus mensajes de ayer?'],
      [0, '¿Prefieres no poder mentir nunca más o que nunca más te crean?'],
      [0, '¿Prefieres comer solo pizza el resto de tu vida o no volver a comerla nunca?'],
      [0, '¿Prefieres que te tatúen el nombre de {p2} o el de tu ex?'],
      [0, '¿Prefieres quedarte sin internet un mes o sin agua caliente un mes?'],
      [0, '¿Prefieres que tu jefe te vea de fiesta a las 5 de la mañana o que tus padres lean este chat de grupo?'],
      [0, '¿Prefieres viajar al pasado o al futuro?'],
      [0, '¿Prefieres que se acabe la fiesta ahora o seguir hasta el amanecer sin poder sentarte?'],
      [1, '¿Prefieres una cita con alguien guapísimo pero aburrido o con alguien normal pero divertidísimo?'],
      [1, '¿Prefieres que tu ex se entere de todo lo que haces o no volver a saber nada de tu ex?'],
      [1, '¿Prefieres una pareja celosa o una pareja que pase de ti?'],
      [1, '¿Prefieres ligar solo por apps o solo en persona?'],
      [1, '¿Prefieres que tu crush lea tus chats con tu mejor amistad o tus búsquedas de Google?'],
      [1, '¿Prefieres casarte con tu primer amor o no haberle conocido nunca?'],
      [1, '¿Prefieres una cita con {p} o con {p2}?'],
      [2, '¿Prefieres liarte esta noche con alguien de este grupo o con alguien que no conoces?'],
      [2, '¿Prefieres besar a tu ex o a tu jefe o jefa?'],
      [2, '¿Prefieres que se filtren tus fotos más atrevidas o tus conversaciones más atrevidas?'],
      [2, '¿Prefieres un rollo increíble de una noche o una relación aburrida de un año?'],
      [2, '¿Prefieres que te pongan los cuernos y no enterarte nunca o enterarte?'],
      [2, '¿Prefieres que tu familia lea tus chats de ligar o tu historial de incógnito?'],
      [3, '¿Prefieres sexo increíble una vez al año o sexo normal todos los días?'],
      [3, '¿Prefieres un trío o un intercambio de parejas?'],
      [3, '¿Prefieres que tus padres te pillen haciéndolo o pillarles tú a ellos?'],
      [3, '¿Prefieres no volver a besar a nadie o no volver a tener sexo?'],
      [3, '¿Prefieres hacerlo en la playa o en un ascensor?'],
      [3, '¿Prefieres una noche con tu crush famoso o una semana con tu crush de verdad?'],
      [3, '¿Prefieres que tu ex cuente tu peor polvo o tu mejor polvo?']
    ],

    duelo: [
      [0, '{p} contra {p2}: piedra, papel o tijera al mejor de tres.'],
      [0, '{p} contra {p2}: duelo de miradas. Quien parpadee o se ría primero, pierde.'],
      [0, '{p} contra {p2}: pulso de pulgares al mejor de tres.'],
      [0, '{p} contra {p2}: por turnos, decid palabras que empiecen por «ca». Quien se quede en blanco o repita, pierde.'],
      [0, '{p} contra {p2}: por turnos, decid marcas de coche. Quien falle, pierde.'],
      [0, '{p} contra {p2}: batalla de rap de 15 segundos por cabeza. El grupo decide.', { min: 3 }],
      [0, '{p} contra {p2}: el grupo elige un animal. Gana la mejor imitación.', { min: 3 }],
      [0, '{p} contra {p2}: a la pata coja. Quien apoye el pie primero, pierde.'],
      [0, '{p} contra {p2}: concurso de caras raras. El grupo vota.', { min: 3 }],
      [0, '{p} contra {p2}: el resto intenta haceros reír. Quien aguante más serio, gana.', { min: 3 }],
      [0, '{p} contra {p2}: el grupo piensa en un famoso y vosotros preguntáis por turnos cosas de sí o no. Quien lo adivine, gana.', { min: 3 }],
      [0, '{p} contra {p2}: decid «El cielo está enladrillado, ¿quién lo desenladrillará?». Gana quien lo diga mejor.', { min: 3 }],
      [0, '{p} contra {p2}: lanzad una bola de papel a un vaso. Tres intentos cada uno.'],
      [0, '{p} contra {p2}: contad hasta 30 por turnos, pero en los múltiplos de 3 hay que decir «Shanghai». Quien falle, pierde.'],
      [0, '{p} contra {p2}: por turnos, decid canciones de reguetón. Quien se quede en blanco, pierde.'],
      [0, '{p} contra {p2}: cadena de memoria. Decid por turnos una palabra repitiendo todas las anteriores. Quien falle, pierde.'],
      [0, '{p} contra {p2}: el grupo pone una canción. Quien adivine antes el título, gana.', { min: 3 }],
      [0, '{p} contra {p2}: quien diga más rápido el nombre completo de todo el grupo, gana.'],
      [0, '{p} contra {p2}: ¿quién conoce mejor al otro? Haceos tres preguntas. Gana quien acierte más.'],
      [1, '{p} contra {p2}: gana la mejor frase para ligar. Vota el grupo.', { min: 3 }],
      [1, '{p} contra {p2}: posad para la portada de una revista romántica. Vota el grupo.', { min: 3 }],
      [2, '{p} contra {p2}: el mejor baile sexy de 10 segundos. Vota el grupo.', { min: 3 }],
      [2, '{p} contra {p2}: intentad seducir al grupo con una sola frase. Gana quien más sonrisas saque.', { min: 3 }]
    ],

    grupo: [
      [0, 'Pagan todas las personas que lleven algo negro.'],
      [0, 'Paga quien tenga menos batería en el móvil. Comprobadlo.', { n: 2 }],
      [0, 'Paga la última persona que llegó a la fiesta.'],
      [0, '¡Brindis! Todo el mundo levanta su vaso y bebe, con o sin alcohol.', { todos: true }],
      [0, 'Paga quien haya mirado el móvil durante la última carta.'],
      [0, 'A la de tres, todo el mundo se toca la nariz. La última persona en hacerlo, paga.'],
      [0, 'Pagan quienes hayan dicho una palabrota en los últimos cinco minutos.'],
      [0, 'Paga quien tenga más notificaciones sin leer.'],
      [0, 'A la de tres, todo el mundo señala a quien mejor viste esta noche. Esa persona elige quién paga.', { min: 3 }],
      [0, 'Silencio absoluto durante 30 segundos. Quien hable primero, paga.', { n: 2 }],
      [0, 'Pagan quienes todavía no hayan bailado esta noche.'],
      [0, '{p} elige a dos personas. Las dos pagan.', { min: 3 }],
      [0, '¡Ronda de agua! Todo el mundo bebe un trago de agua. Sí, también quien bebe alcohol.', { todos: true }],
      [0, 'A la de tres, todo el mundo dice un número del 1 al 5. Quienes coincidan, pagan.'],
      [0, 'Brindis por {p}: todo el mundo bebe de su vaso y {p} da las gracias con un discurso.', { todos: true }],
      [0, '{p} reparte tres pagos entre quien quiera. Puede darlos todos a la misma persona.'],
      [0, 'Pagan quienes no hayan pagado todavía en esta partida.', { n: 2 }],
      [0, 'A la de tres, todo el mundo señala a quien crea que más ha mentido en este juego. Paga quien más votos tenga.', { min: 3, n: 2 }],
      [0, 'Todo el mundo enseña el último emoji que ha usado. Paga quien tenga el más raro.'],
      [0, 'Pagan quienes hayan hablado mal de alguien hoy. Sed sinceros.'],
      [0, '{p} elige a alguien. Esa persona y {p} pagan juntas.'],
      [0, 'Paga quien tenga más fotos en la galería. Comprobadlo.'],
      [1, 'Pagan quienes estén sin pareja.'],
      [1, 'Pagan quienes hayan tenido una cita este mes.'],
      [1, 'Pagan quienes tengan una app de ligar instalada ahora mismo.'],
      [1, 'Pagan quienes tengan en el móvil una foto que no enseñarían aquí.'],
      [1, 'Pagan quienes hayan tenido un crush con alguien de aquí. Nadie tiene que decir con quién.'],
      [2, 'Pagan quienes hayan dado un beso esta semana.'],
      [2, 'Pagan quienes hayan escrito a un ex este año.'],
      [2, 'Pagan quienes se hayan liado con alguien en el último mes.'],
      [2, 'Pagan quienes hayan mandado alguna vez una foto subida de tono.', { n: 2 }],
      [3, 'Pagan quienes lo hayan hecho esta semana.'],
      [3, 'Pagan quienes tengan un juguete sexual en casa.'],
      [3, 'Pagan quienes lo hayan hecho alguna vez en un sitio público.', { n: 2 }]
    ],

    categoria: [
      [0, 'Marcas de cerveza'],
      [0, 'Bebidas sin alcohol'],
      [0, 'Países de Asia'],
      [0, 'Personajes de Disney'],
      [0, 'Canciones del verano'],
      [0, 'Futbolistas'],
      [0, 'Series de Netflix'],
      [0, 'Ciudades de España'],
      [0, 'Palabras que rimen con «fiesta»'],
      [0, 'Excusas para no ir a trabajar'],
      [0, 'Marcas de ropa'],
      [0, 'Cantantes o grupos de los 2000'],
      [0, 'Cócteles'],
      [0, 'Cosas que se pierden en una fiesta'],
      [0, 'Platos de comida china'],
      [0, 'Personajes de los Simpson'],
      [0, 'Cosas que se pueden comprar en un chino'],
      [0, 'Cosas que dices cuando vas borracho'],
      [0, 'Canciones de reguetón'],
      [1, 'Cosas que se hacen en una primera cita'],
      [1, 'Apodos cariñosos para una pareja'],
      [1, 'Sitios donde ligar'],
      [1, 'Frases para ligar'],
      [2, 'Excusas para no volver a casa'],
      [2, 'Partes del cuerpo que te parecen sexis'],
      [2, 'Señales de que alguien quiere liarse contigo'],
      [3, 'Posturas sexuales'],
      [3, 'Sitios donde hacerlo'],
      [3, 'Juguetes sexuales']
    ],

    regla: [
      [0, 'Nadie puede decir «beber» ni «trago». Quien lo diga, paga.', { dura: 8 }],
      [0, '{p} manda en los pulgares: cuando ponga el pulgar en la mesa, todo el mundo tiene que hacerlo. La última persona, paga.', { dura: 10 }],
      [0, 'Hay que hablar como en una peli de piratas. Quien se olvide, paga.', { dura: 5 }],
      [0, 'Prohibido señalar con el dedo. Quien lo haga, paga.', { dura: 8 }],
      [0, '{p} manda en las preguntas: quien conteste a una pregunta de {p}, paga.', { dura: 8 }],
      [0, 'Prohibido decir nombres. Usad apodos. Quien diga un nombre, paga.', { dura: 6 }],
      [0, 'Quien diga «tío» o «tía», paga.', { dura: 8 }],
      [0, 'El vaso se coge con la mano izquierda, lleve lo que lleve. Quien use la derecha, paga.', { dura: 8 }],
      [0, 'Prohibido tocar el móvil. Quien lo toque, paga.', { dura: 6 }],
      [0, '{p} y {p2} van en pack: cuando una de las dos personas paga, la otra también.', { dura: 10 }],
      [0, 'Hay que acabar cada frase con «en Shanghai». Quien se olvide, paga.', { dura: 5 }],
      [0, 'Prohibido decir «sí» y «no». Quien lo diga, paga.', { dura: 5 }],
      [0, '{p} es el espejo de {p2}: tiene que copiar todo lo que haga. Si se le olvida, paga.', { dura: 5 }],
      [0, 'Cada vez que {p} se ría, paga.', { dura: 6 }],
      [0, '{p} y {p2} solo pueden hablarse cantando. Quien hable normal, paga.', { dura: 6 }],
      [0, 'Quien diga una palabrota, paga.', { dura: 8 }],
      [1, '{p} tiene que decirle un piropo a quien hable justo antes. Si se le olvida, paga.', { dura: 6 }],
      [1, '{p} y {p2} tienen que ir de la mano, si os parece bien. Si os soltáis, pagáis.', { dura: 6 }],
      [2, 'Cada vez que alguien diga «sexo», paga quien esté a su izquierda.', { dura: 8 }]
    ]
  };

  var CASTIGOS = [
    [1, 'Haz 10 sentadillas mientras el grupo cuenta.'],
    [1, 'Di sin equivocarte: «Pablito clavó un clavito, ¿qué clavito clavó Pablito?».'],
    [1, 'Haz tu mejor pose de modelo durante 5 segundos.'],
    [1, 'Cuenta un chiste malo.'],
    [1, 'Imita al animal que elija el grupo.'],
    [1, 'Habla como un robot hasta tu próximo turno.'],
    [1, 'Di en 10 segundos cinco palabras que empiecen por la letra que elija el grupo.'],
    [1, 'Haz un brindis de 10 segundos por la persona de tu izquierda.'],
    [1, 'Da un sorbo a tu bebida con el meñique levantado y acento pijo.'],
    [1, 'Haz una reverencia exagerada a todo el grupo.'],
    [1, 'Aguanta 15 segundos sin reírte mientras el grupo intenta hacerte reír.'],
    [1, 'Canta «Cumpleaños feliz» con voz de ópera.'],
    [1, 'Di tres cosas buenas de la persona de tu derecha.'],
    [1, 'Haz el ruido de un coche de carreras durante 5 segundos.'],
    [2, 'Baila 20 segundos la canción que elija el grupo.'],
    [2, 'Haz 20 sentadillas mientras el grupo cuenta.'],
    [2, 'Deja que el grupo te ponga un mote hasta tu próximo turno.'],
    [2, 'Aguanta 30 segundos haciendo la plancha.'],
    [2, 'Canta el estribillo de la canción que elija el grupo.'],
    [2, 'Habla con el acento que elija el grupo hasta tu próximo turno.'],
    [2, 'Haz de camarero: rellena el vaso de quien te lo pida en la próxima carta.'],
    [2, 'No puedes decir «sí» ni «no» hasta tu próximo turno.'],
    [2, 'Vende como en la teletienda el objeto que elija el grupo.'],
    [2, 'Imita a alguien del grupo hasta que lo adivinen.']
  ];

  var cards = [];
  Object.keys(RAW).forEach(function (type) {
    RAW[type].forEach(function (entry, i) {
      var extra = entry[2] || {};
      var card = { id: type + '-' + i, type: type, hot: entry[0], text: entry[1] };
      if (extra.n) card.n = extra.n;
      if (extra.dura) card.dura = extra.dura;
      if (extra.todos) card.todos = true;
      if (extra.min) card.min = extra.min;
      cards.push(card);
    });
  });

  var castigos = CASTIGOS.map(function (entry, i) {
    return { id: 'castigo-' + i, nivel: entry[0], text: entry[1] };
  });

  var data = { cards: cards, castigos: castigos };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = data;
  } else {
    root.PREVIA_DATA = data;
  }
})(typeof window !== 'undefined' ? window : this);
